default_stages: [pre-commit]
fail_fast: true
default_language_version:
  golang: system

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: jsonschema/api-docs.md|internal/graphapi/generated/.+\.go|internal/graphapi/clientschema/.+\.graphql|node_modules/.*|\.git/.*
      - id: detect-private-key
        exclude: node_modules/.*|\.git/.*
  - repo: https://github.com/google/yamlfmt
    rev: v0.17.2
    hooks:
      - id: yamlfmt
  - repo: https://github.com/adhtruong/mirrors-typos
    rev: v1.37.2
    hooks:
      - id: typos
        exclude: node_modules/.*|\.git/.*
  - repo: local
    hooks:
      - id: format-graphql
        name: Format GraphQL
        description: This hook formats GraphQL schemas
        entry: npx format-graphql@1.5.0 --write=true
        language: node
        files: 'query/.*\.graphql$'
# - repo: local
#   hooks:
#     - id: generate
#       name: Run Go Generate
#       description: This hook runs go generate on the project
#       entry: bash -c 'find . -name "*.go" -exec grep -l "^//go:generate" {} \; | head -1 | xargs -I {} go generate {}'
#       language: system
#       files: \.(go|graphql|tmpl)$
